package gocensus_test

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/arloliu/gocensus"
)

func TestAnalyzeEmptyGoModule(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "go.mod", "module example.com/app\n\ngo 1.21\n")

	result, err := gocensus.Analyze(context.Background(), gocensus.Options{Root: dir})
	if err != nil {
		t.Fatalf("Analyze returned error: %v", err)
	}

	if result.Root != dir {
		t.Fatalf("Root = %q, want %q", result.Root, dir)
	}
	if result.ModulePath != "example.com/app" {
		t.Fatalf("ModulePath = %q, want example.com/app", result.ModulePath)
	}
	if result.Files.Total != 0 {
		t.Fatalf("Files.Total = %d, want 0", result.Files.Total)
	}
	if len(result.Packages) != 0 {
		t.Fatalf("Packages length = %d, want 0", len(result.Packages))
	}
	if len(result.FileMetrics) != 0 {
		t.Fatalf("FileMetrics length = %d, want 0", len(result.FileMetrics))
	}
}

func TestAnalyzeCountsRepositoryMetrics(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "go.mod", "module example.com/app\n\ngo 1.21\n")
	writeFile(t, dir, ".gitignore", "ignored.go\n")
	writeFile(t, dir, "main.go", "package main\n\nfunc main() {}\n")
	writeFile(t, dir, "main_test.go", `package main

import "testing"

func TestMain(t *testing.T) {
	cases := []struct{ name string }{
		{name: "one"},
		{name: "two"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {})
	}
	for _, name := range loadCases() {
		t.Run(name, func(t *testing.T) {})
	}
}
`)
	writeFile(t, dir, "mock_client.go", "package main\n\ntype mockClient struct{}\n")
	writeFile(t, dir, "service.pb.go", "// Code generated by protoc; DO NOT EDIT.\npackage main\n")
	writeFile(t, dir, "ignored.go", "package main\n")

	result, err := gocensus.Analyze(context.Background(), gocensus.Options{
		Root: dir,
	})
	if err != nil {
		t.Fatalf("Analyze returned error: %v", err)
	}

	if result.Files.Total != 4 {
		t.Fatalf("Files.Total = %d, want 4", result.Files.Total)
	}
	if result.Files.Production != 1 || result.Files.Tests != 1 || result.Files.Mocks != 1 || result.Files.Generated != 1 {
		t.Fatalf("file buckets = %#v", result.Files)
	}
	if result.Tests.Tests != 1 {
		t.Fatalf("Tests.Tests = %d, want 1", result.Tests.Tests)
	}
	if result.Tests.StaticSubtests != 2 {
		t.Fatalf("Tests.StaticSubtests = %d, want 2", result.Tests.StaticSubtests)
	}
	if result.Tests.DynamicSubtestSites != 1 {
		t.Fatalf("Tests.DynamicSubtestSites = %d, want 1", result.Tests.DynamicSubtestSites)
	}
	if len(result.FileMetrics) != 4 {
		t.Fatalf("FileMetrics length = %d, want 4", len(result.FileMetrics))
	}
}

func writeFile(t *testing.T, root string, rel string, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
