package classify_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/arloliu/gocensus/internal/classify"
)

func TestFileKind(t *testing.T) {
	root := t.TempDir()
	cases := []struct {
		rel     string
		content string
		want    classify.Kind
	}{
		{rel: "main.go", content: "package main\n", want: classify.KindProduction},
		{rel: "main_test.go", content: "package main\n", want: classify.KindTest},
		{rel: "mock_client.go", content: "package main\n", want: classify.KindMock},
		{rel: "client_mock.go", content: "package main\n", want: classify.KindMock},
		{rel: "service.pb.go", content: "package main\n", want: classify.KindGenerated},
		{rel: "generated.go", content: "// Code generated by tool; DO NOT EDIT.\npackage main\n", want: classify.KindGenerated},
	}

	for _, tc := range cases {
		t.Run(tc.rel, func(t *testing.T) {
			path := filepath.Join(root, filepath.FromSlash(tc.rel))
			if err := os.WriteFile(path, []byte(tc.content), 0o644); err != nil {
				t.Fatal(err)
			}
			got, err := classify.File(path)
			if err != nil {
				t.Fatal(err)
			}
			if got != tc.want {
				t.Fatalf("File(%q) = %q, want %q", tc.rel, got, tc.want)
			}
		})
	}
}
